#!/usr/bin/env bash
# Idempotent dotfiles bootstrap. Safe to re-run any time.
set -euo pipefail

DOTFILES_DIR="$(cd "$(dirname "$0")" && pwd)"

# Stow packages (top-level dirs) to link into $HOME. Add your own here, and keep
# this in sync with DOTFILES_PACKAGES in shell/.zshrc.
PACKAGES=(shell git bin)

# The dotfiles-update zsh plugin — the update/apply mechanism.
PLUGIN_REPO="https://github.com/ccollins/dotfiles-update"

info()    { printf "\n\033[1;34m==> %s\033[0m\n" "$1"; }
success() { printf "\033[1;32m    %s\033[0m\n" "$1"; }
warn()    { printf "\033[1;33m    %s\033[0m\n" "$1"; }

# --- Homebrew + packages (macOS) ---------------------------------------------
if [[ "$OSTYPE" == darwin* ]]; then
  if ! command -v brew &>/dev/null; then
    info "Installing Homebrew..."
    /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
    eval "$(/opt/homebrew/bin/brew shellenv)"
  fi
  if [[ -f "$DOTFILES_DIR/Brewfile" ]]; then
    info "Installing Homebrew packages..."
    brew bundle --file="$DOTFILES_DIR/Brewfile"
  fi
fi

# --- Oh My Zsh ---------------------------------------------------------------
if [[ ! -d "$HOME/.oh-my-zsh" ]]; then
  info "Installing Oh My Zsh..."
  RUNZSH=no KEEP_ZSHRC=yes sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
fi

# --- dotfiles-update plugin --------------------------------------------------
info "Installing the dotfiles-update plugin..."
ZSH_CUSTOM="${ZSH_CUSTOM:-$HOME/.oh-my-zsh/custom}"
PLUGIN_DIR="$ZSH_CUSTOM/plugins/dotfiles-update"
if [[ -d "$PLUGIN_DIR/.git" ]]; then
  git -C "$PLUGIN_DIR" pull --ff-only --quiet && success "Updated dotfiles-update"
else
  git clone --quiet "$PLUGIN_REPO" "$PLUGIN_DIR" && success "Cloned dotfiles-update"
fi

# --- Stow packages -----------------------------------------------------------
if ! command -v stow &>/dev/null; then
  warn "GNU stow not found — install it (brew install stow) and re-run"; exit 1
fi
info "Linking packages with stow..."
for pkg in "${PACKAGES[@]}"; do
  # NOTE: stow won't overwrite a real (non-symlink) file. If you already have a
  # ~/.zshrc etc., back it up first, then re-run.
  if [[ -d "$DOTFILES_DIR/$pkg" ]]; then
    stow -d "$DOTFILES_DIR" -t "$HOME" --restow "$pkg" && success "Linked $pkg"
  fi
done

# --- Record the applied commit (baseline for the update check) ---------------
CACHE="${ZSH_CACHE_DIR:-$HOME/.oh-my-zsh/cache}"
mkdir -p "$CACHE"
if git -C "$DOTFILES_DIR" rev-parse HEAD > "$CACHE/.dotfiles-installed" 2>/dev/null; then
  success "Recorded installed commit"
fi

# --- Reconcile app-managed config files --------------------------------------
# For configs an app owns/rewrites (so they can't be stowed), regenerate them from
# a tracked base while preserving machine-local keys. Edit the list in
# bin/.local/bin/reconcile-managed. No-op until you add entries.
if command -v jq &>/dev/null; then
  DOTFILES="$DOTFILES_DIR" "$DOTFILES_DIR/bin/.local/bin/reconcile-managed" && success "Reconciled managed configs"
else
  warn "jq not found — skipped managed-config reconcile (brew install jq, then re-run)"
fi

# --- Optional: machine-local secrets -----------------------------------------
# Uncomment and adapt if you keep secrets in a password manager (e.g. 1Password
# CLI `op`). Writes ~/.zshrc.local (git-ignored) with env vars your .zshrc sources.
#
# if command -v op &>/dev/null; then
#   umask 077
#   {
#     echo "# Generated by bootstrap.sh — do not commit."
#     echo "export SOME_TOKEN=\"$(op read 'op://Vault/Item/credential')\""
#   } > "$HOME/.zshrc.local"
#   success "Wrote ~/.zshrc.local"
# fi

info "Bootstrap complete! Open a new terminal, or run: exec zsh"
